name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  validacao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Instalar Dependências
        run: pnpm install

      - name: Executar Linter (Qualidade de Código)
        working-directory: ./backend
        run: pnpm lint

      - name: Validar Tipagem (Typecheck)
        working-directory: ./backend
        run: pnpm typecheck

      - name: Build de Produção
        working-directory: ./backend
        run: pnpm build